spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    properties:
      hibernate.format_sql : true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/setterMethod?serverTimezone=Asia/Seoul
    username: root
    password: 'xcz119'
    data: classpath:/data.sql